### ISSUE TITLE
Needs too much pressure (Ubuntu 18.04)

### ISSUE THREAD

**Issue by tasos14** [robotrovsky/Linux-Magic-Trackpad-2-Driver#32]
I'm on Ubuntu 18.04 with 4.20 kernel, on wireless mode scrolling needs a lot of pressure. When connected it works fine.
I have added the quirks file to `/usr/share/libinput/.quirks` as suggested by this comment https://github.com/robotrovsky/Linux-Magic-Trackpad-2-Driver/issues/24#issuecomment-434697180
But the problem still persists.

**Comment by dos1** [comment]
Use `libinput quirks list /dev/input/eventX` to verify whether the quirks file is really applied.

For the reference, this is my `/etc/libinput/local-overrides.quirks` that works for me in both modes:
```
[Touchpad pressure override]
MatchName=*Magic Trackpad 2
AttrPressureRange=2:0
```

**Comment by tasos14** [comment]
I tried to run `libinput quirks list /dev/input/eventX` but i got an error saying that quirks is not a libinput command, so I checked to see which version I have.
The installed libinput version is 1.10.4 and the latest is 1.12.3. I think that might be the reason that it can not detect the local-overrides.quirks.

I didn't find a way to update to the latest version, is my only option to build from source ?

**Comment by dos1** [comment]
You may also try `libinput list-quirks`, I think that command got renamed recently.

**Comment by tasos14** [comment]
I fixed it. I built from source following these instructions [https://wayland.freedesktop.org/libinput/doc/latest/building.html#building](url)
now I have the latest version and wireless works fine with the quirks file.

**Comment by whot** [comment]
bug for libinput was filed here: https://gitlab.freedesktop.org/libinput/libinput/issues/280
