### ISSUE TITLE
Magic Mouse 2 - Scroll not working 

### ISSUE THREAD

**Issue by romanAbrahamovic** [robotrovsky/Linux-Magic-Trackpad-2-Driver#33]
I finish instalation by instructions in readme file. 

I still cannot scroll on my MM2. Is there a something which I missing? 

```
kernel: 
4.18.5-041805-generic
```

```
+ dkms_name=hid-magicmouse-dkms
+ dkms_version=4.18+magictrackpad2
+++ dirname ./install.sh
++ cd .
++ pwd
+ DIR=/***/***/Linux-Magic-Trackpad-2-Driver/scripts
+ dkms status -m hid-magicmouse-dkms -v 4.18+magictrackpad2
+ egrep '(added|built|installed)'
+ dkms status -m hid-magicmouse-dkms -v 4.18+magictrackpad2
+ egrep '(built|installed)'
+ dkms status -m hid-magicmouse-dkms -v 4.18+magictrackpad2
+ egrep '(installed)'
```

```
Dist: 

Ubuntu 18.04

```

If I used kernel v.4.20 or 4.15 still had a same problem with scroll. Thank you for advice.

**Comment by Liemaeu** [comment]
I have the same problem (Ubuntu 18.04.2, 4.18.0-16-generic)

**Comment by mwyborski** [comment]
You mean the Magic Trackpad 2, not the Magic Mouse 2, right?
You can just checkout the version below and you dont need the quirks file, everything should work:
https://github.com/robotrovsky/Linux-Magic-Trackpad-2-Driver/tree/63187c13bb198609689460bbd1a99a4f622b5d83

**Comment by romanAbrahamovic** [comment]
@robotrovsky Magic Mouse 2, not Magic Trackpad 2. Support this drive magic mouse 2?

**Comment by mwyborski** [comment]
@romanAbrahamovic no this driver doesn't support the Magic Mouse 2. Only Magic Mouse I and Magic Trackpad I + II

**Comment by kubaplas** [comment]
I can confirm that the driver works with Magic Mouse 2, but it needs to be manualy loaded - 
see https://forum.manjaro.org/t/apple-magic-mouse-2-not-working-kernel-4-20/72236/5

**Comment by stubbulon5** [comment]
@romanAbrahamovic how much work would supporting Magic Mouse 2 take? (Enabling scrolling, that is)

I recon there would be many Linux users happy to buy you a coffee if you got this working...

**Comment by Liemaeu** [comment]
@stubbulon5 Me for example!

**Comment by DaBlitzStein** [comment]
Scroll not working on 5.0.23 ubuntu 18.04 .

**Comment by stubbulon5** [comment]
@robotrovsky , is seems Magic Trackpad 2 scrolling works but not Magic Mouse 2 scrolling. How feasible would a fix for this be? 

Much respect for the work you've done so far.

**Comment by gchehab** [comment]
I am using this fork patched to work with magic mouse 2: [https://github.com/rohitpid/Linux-Magic-Trackpad-2-Driver](https://github.com/rohitpid/Linux-Magic-Trackpad-2-Driver).
The (virtual) wheel using single finger swipe works ok using libinput driver option.
It would be nice to have it merged with the main version -- I guess I could do a merge request, should it be acceptable.

**Comment by txtad** [comment]
> It would be nice to have it merged with the main version -- I guess I could do a merge request, should it be acceptable.

That would be wonderful. I've converted a Mac mini to an Intel Nuc running Ubuntu, but I've kept the mini's keyboard and mouse. I was happily surprised that they are working at the login screen, but then quickly disappointed that scrolling with the Magic Mouse 2 wasn't working. I was honestly surprised that it didn't "just work".

**Comment by leftdevel** [comment]
Sorry for posting on an old thread. I got the magic mouse working even with the scroll feature, but scrolling is quite slow, just to scroll this thread it takes me 7 swipes. Do you know how I can increase the scroll speed?

Thank you.

**Comment by imanm93** [comment]
@leftdevel could you please describe how you got the scrolling to work on the magic mouse 2?

Also will there be any updates to support this for ubuntu 20.04 - scrolling doesn't seem to work on this version (kernel v5.4.0-42-generic

Thanks in advance!

**Comment by maomorales** [comment]
@imanm93 follow the instructions from rohitpid branch's readme. Make/compile and then run:

sudo rmmod hid-magicmouse
sudo insmod ./hid-magicmouse.ko middle_click_3finger=1

That worked form in 20.04, enjoy the scrolling! :D

**Comment by akozyreva** [comment]
@maomorales for me your decision works, but every time, when mouse is disconnected with bluetooth or computer sleeps for a while, scrolling doesn't work again and I need every time run these commands
```
sudo rmmod hid-magicmouse
sudo insmod ./hid-magicmouse.ko middle_click_3finger=1
```
Does anybody have the same execution? How to fix it?

**Comment by maomorales** [comment]
@akozyreva I ended up changing the Mouse. I couldn't solve it and the time I was spending there was not a smart use of my time 😄 

I guess you can create some automated script that is automatically called when some of those events happen. But not the nicest solution.
