### ISSUE TITLE
Ubuntu 18.04.2 no scrolling

### ISSUE THREAD

**Issue by Liemaeu** [robotrovsky/Linux-Magic-Trackpad-2-Driver#36]
My System:
Ubuntu 18.04.2 (amd64)
Kernel: 4.18.0-16-generic

I can't scroll with my Magic Mouse 2. 

There was no libinput directory in /etc, so I created it (sudo mkdir /etc/libinput) and placed the local-overrides.quirks file in it. But it still doesn't work.

**Comment by mwyborski** [comment]
Have you compiled the kernel module yourself? It is not included in 4.18 it is included from 4.20 onwards.
You can just checkout the version below and you dont need the quirks file, everything should work:
https://github.com/robotrovsky/Linux-Magic-Trackpad-2-Driver/tree/63187c13bb198609689460bbd1a99a4f622b5d83

**Comment by tegk** [comment]
Same here with Linux 5.0.7-050007-generic on Ubuntu 18.10. Mouse works with right and left click but no scrolling. Any tips to get it working?

**Comment by dos1** [comment]
At first glance I'd say that it's probably unrelated to the driver, but to configuration of input driver in your display servers/desktop environments.

**Comment by mwyborski** [comment]
I recommend to wait a few days and upgrade to Ubuntu 19.04, there everything works out of the box.
