### ISSUE TITLE
Acceleration

### ISSUE THREAD

**Issue by bradley-varol** [robotrovsky/Linux-Magic-Trackpad-2-Driver#41]
I've installed this driver on Ubuntu 18.04, Kernal 4.18, and I notice that acceleration is enabled.

Can I disable it?

**Comment by dos1** [comment]
It's not up to the driver - you have to configure it in whichever windowing system and desktop environment you're using.

**Comment by bradley-varol** [comment]
Alright, thanks.

**Comment by bradley-varol** [comment]
Any help would be appreciated;

I installed a clean copy of Ubuntu 18, installed Gnome Tweaks and set the acceleration profile to "flat". This removed acceleration. I then installed this driver and acceleration is back...
