### ISSUE TITLE
Support for Linux Kernel 5.2.15 please.

### ISSUE THREAD

**Issue by bionicmac** [robotrovsky/Linux-Magic-Trackpad-2-Driver#46]
I used this driver well into the 5.* and until now it worked fine. I probably jumped from 5.1.* to 5 .2.15 though. I've tried this on Fedora with kernel version mentioned above and it doesn't work. Thanks so much for the wonderful work!

**Comment by frumble** [comment]
Is working here on 5.3.1 on Arch.

**Comment by dos1** [comment]
This driver is already included in mainline since 5.0.
