### ISSUE TITLE
Support for Secondary Click

### ISSUE THREAD

**Issue by hiradyazdan** [robotrovsky/Linux-Magic-Trackpad-2-Driver#47]
Hi, I was wondering if this driver can support a secondary click that can be activated and have option to choose to click in bottom right corner as well? If not, it would be great to support it.

Thanks

**Comment by dos1** [comment]
Unless you mean something like "force touch", it's not the driver's job. You should rather look at something like libinput instead. Secondary button clicks work just fine for me with two fingers, and having virtual buttons in bottom corners worked fine after applying appropiate libinput quirks last time I checked.

**Comment by hiradyazdan** [comment]
Oh! Thanks, I didn't realize that. I guess now I have to figure out how to configure the `libinput`'s button areas and clickfinger behavior, right?

Edit: So far, my search over this has been unsuccessful @dos1. If you have a clear vision on how this can be implemented I'd be grateful to hear that.

**Comment by hiradyazdan** [comment]
FYI, `libinput` quirks on their own does not take permanent effect and solves this problem. It is the desktop environment which overrides/forces its own settings. So in my case was gnome which uses libinput overriding xorg config, and following command worked permanently:

```shell
gsettings set org.gnome.desktop.peripherals.touchpad click-method 'areas'
```
