### ISSUE TITLE
Is there any way to increase polling rate?

### ISSUE THREAD

**Issue by dm17** [robotrovsky/Linux-Magic-Trackpad-2-Driver#48]
Do you know if it would be possible to increase the polling rate of the trackpad? Seems like this is mostly unexplored on trackpads.
Thanks!

**Comment by mwyborski** [comment]
@dm17 the reports are not polled if i remember correctly, the Trackpad just sends the reports. That said i think USB performs a little better than Bluetooth.

**Comment by dm17** [comment]
I didn't realize trackpads were not polled. I'll have to look into that more. Thanks.
