### ISSUE TITLE
Apple Magic Trackpad (A1339) turns off every few minutes.

### ISSUE THREAD

**Issue by ScherbakovAl** [robotrovsky/Linux-Magic-Trackpad-2-Driver#64]
Apple Magic Trackpad (A1339) turns off every few minutes. I am using Ubuntu 23.04.
libinput --version: 1.22.1.
The trackpad periodically turns off and then, after a dozen seconds, reconnects. I'll attach a report from hciconfig, bluetoothctl, syslog, sudo btmon:
https://pastebin.com/3A9EXusp
I love using the trackpad, but these reconnections make interacting with it impossible. This trackpad works great with android phone and doesn't have any reconnects. Connectivity is constantly lost with Ubuntu. This also happens with different usb bluetooth dongles.
This issue has been reported here:
https://bugs.launchpad.net/linux/+bug/1834085
What other logs and reports do I need to provide in order to sort out the problem?
Where else can you write about it?
Thank you!

**Comment by mwyborski** [comment]
@ScherbakovAl please send your bug report to the linux kernel mailing list. Sorry, but I won't have time to check and fix this and also the mailing list is the right channel to get this fixed.
